# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CryptoWalletVIPER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoWalletVIPER
	pod 'Kingfisher', '6.3.0'
	pod 'RxSwift', '6.2.0'
    	pod 'RxCocoa', '6.2.0'

  target 'CryptoWalletVIPERTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoWalletVIPERUITests' do
    # Pods for testing
  end

end
